apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-component
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: bgapp
      role: db
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bgapp
        role: db
    spec:
      containers:
      - name: prod-container
        image: merev/db-component
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "12345"
